//some samples at https://casual-effects.com/data/

// const MODEL_URL = './models/planes.glb'; 
//hdri image orignal source: 'https://cdn.polyhaven.com/asset_img/primary/aerodynamics_workshop.png?height=150'
export const HDR_FILES = [
	{ name: "Adams Place Bridge", url: "/hdri/adams_place_bridge_1k.hdr", preview: "/hdri/adams_place_bridge.webp" },
	{ name: "Aerodynamics Workshop", url: "/hdri/aerodynamics_workshop_1k.hdr", preview: "/hdri/aerodynamics_workshop.webp" },
	{ name: "Aristea Wreck Pure Sky", url: "/hdri/aristea_wreck_puresky_1k.hdr", preview: "/hdri/aristea_wreck_puresky.webp" },
	{ name: "Auto Shop", url: "/hdri/autoshop_01_1k.hdr", preview: "/hdri/autoshop_01.webp" },
	{ name: "Blocky Photo Studio", url: "/hdri/blocky_photo_studio_1k.hdr", preview: "/hdri/blocky_photo_studio.webp" },
	{ name: "Brown Photo Studio 01", url: "/hdri/brown_photostudio_01_1k.hdr", preview: "/hdri/brown_photostudio_01.webp" },
	{ name: "Brown Photo Studio 02", url: "/hdri/brown_photostudio_02_1k.hdr", preview: "/hdri/brown_photostudio_02.webp" },
	{ name: "Brown Photo Studio 06", url: "/hdri/brown_photostudio_06_1k.hdr", preview: "/hdri/brown_photostudio_06.webp" },
	{ name: "Brown Photo Studio 07", url: "/hdri/brown_photostudio_07_1k.hdr", preview: "/hdri/brown_photostudio_07.webp" },
	{ name: "Chinese Garden", url: "/hdri/chinese_garden_1k.hdr", preview: "/hdri/chinese_garden.webp" },
	{ name: "Christmas Photo Studio 04", url: "/hdri/christmas_photo_studio_04_2k.hdr", preview: "/hdri/christmas_photo_studio_04.webp" },
	{ name: "Christmas Photo Studio 05", url: "/hdri/christmas_photo_studio_05_2k.hdr", preview: "/hdri/christmas_photo_studio_05.webp" },
	{ name: "Christmas Photo Studio 07", url: "/hdri/christmas_photo_studio_07_1k.hdr", preview: "/hdri/christmas_photo_studio_07.webp" },
	{ name: "Circus Arena", url: "/hdri/circus_arena_1k.hdr", preview: "/hdri/circus_arena.webp" },
	{ name: "Comfy Cafe", url: "/hdri/comfy_cafe_2k.hdr", preview: "/hdri/comfy_cafe.webp" },
	{ name: "Dancing Hall", url: "/hdri/dancing_hall_1k.hdr", preview: "/hdri/dancing_hall.webp" },
	{ name: "Drachenfels Cellar", url: "/hdri/drachenfels_cellar_1k.hdr", preview: "/hdri/drachenfels_cellar.webp" },
	{ name: "Hall of Mammals", url: "/hdri/hall_of_mammals_2k.hdr", preview: "/hdri/hall_of_mammals.webp" },
	{ name: "Herkulessaulen", url: "/hdri/herkulessaulen_2k.hdr", preview: "/hdri/herkulessaulen.webp" },
	{ name: "Hilly Terrain", url: "/hdri/hilly_terrain_01_1k.hdr", preview: "/hdri/hilly_terrain_01.webp" },
	{ name: "Kloppenheim", url: "/hdri/kloppenheim_05_1k.hdr", preview: "/hdri/kloppenheim_05.webp" },
	{ name: "Leadenhall Market", url: "/hdri/leadenhall_market_1k.hdr", preview: "/hdri/leadenhall_market.webp" },
	{ name: "Modern Buildings", url: "/hdri/modern_buildings_2_1k.hdr", preview: "/hdri/modern_buildings_2.webp" },
	{ name: "Narrow Moonlit Road", url: "/hdri/narrow_moonlit_road_1k.hdr", preview: "/hdri/narrow_moonlit_road.webp" },
	{ name: "Noon Grass", url: "/hdri/noon_grass_1k.hdr", preview: "/hdri/noon_grass.webp" },
	{ name: "Peppermint Powerplant", url: "/hdri/peppermint_powerplant_1k.hdr", preview: "/hdri/peppermint_powerplant.webp" },
	{ name: "Phalzer Forest", url: "/hdri/phalzer_forest_01_1k.hdr", preview: "/hdri/phalzer_forest_01.webp" },
	{ name: "Photo Studio", url: "/hdri/photo_studio_01_2k.hdr", preview: "/hdri/photo_studio_01.webp" },
	{ name: "Photo Studio Loft Hall", url: "/hdri/photo_studio_loft_hall_2k.hdr", preview: "/hdri/photo_studio_loft_hall.webp" },
	{ name: "Rainforest Trail", url: "/hdri/rainforest_trail_1k.hdr", preview: "/hdri/rainforest_trail.webp" },
	{ name: "Sepulchral Chapel Rotunda", url: "/hdri/sepulchral_chapel_rotunda_1k.hdr", preview: "/hdri/sepulchral_chapel_rotunda.webp" },
	{ name: "St. Peter's Square Night", url: "/hdri/st_peters_square_night_1k.hdr", preview: "/hdri/st_peters_square_night.webp" },
	{ name: "Studio Small 05", url: "/hdri/studio_small_05_1k.hdr", preview: "/hdri/studio_small_05.webp" },
	{ name: "Studio Small 09", url: "/hdri/studio_small_09_1k.hdr", preview: "/hdri/studio_small_09.webp" },
	{ name: "Thatch Chapel", url: "/hdri/thatch_chapel_1k.hdr", preview: "/hdri/thatch_chapel.webp" },
	{ name: "Urban Alley", url: "/hdri/urban_alley_01_2k.hdr", preview: "/hdri/urban_alley_01.webp" },
	{ name: "Vestibule", url: "/hdri/vestibule_1k.hdr", preview: "/hdri/vestibule.webp" },
	{ name: "Vintage Measuring Lab", url: "/hdri/vintage_measuring_lab_1k.hdr", preview: "/hdri/vintage_measuring_lab.webp" },
	{ name: "Wasteland Clouds Pure Sky", url: "/hdri/wasteland_clouds_puresky_2k.hdr", preview: "/hdri/wasteland_clouds_puresky.webp" },
	{ name: "Whale Skeleton", url: "/hdri/whale_skeleton_2k.hdr", preview: "/hdri/whale_skeleton.webp" },
];
// export const MODEL_FILES = [
// 	{ name: "3D Home Layout", url: "3d-home-layout/scene.glb" },
// 	{ name: "Astraia", url: "astraia/scene.gltf" },
// 	{ name: "Bao Robot", url: "bao-robot/bao-robot.glb" },
// 	{ name: "Botanist's Greenhouse", url: "botanists-greenhouse/scene.gltf" },
// 	{ name: "Botanist's Study", url: "botanists-study/scene.gltf" },
// 	{ name: "Colour Drafts", url: "colourdrafts/scene.glb" },
// 	{ name: "Diamond", url: "diamond/diamond.glb" },
// 	{ name: "Dragon Attenuation", url: "dragon-attenuation/DragonAttenuation.glb" },
// 	{ name: "Dream Apartment", url: "dream-apartment/dream-apartment.glb" },
// 	{ name: "Drone", url: "drone/drone.glb" },
// 	{ name: "Dungeon Warkarma", url: "dungeon-warkarma/scene.gltf" },
// 	{ name: "Gelatinous Cube", url: "gelatinous-cube/scene.gltf" },
// 	{ name: "Guitar", url: "guitar/guitar.glb" },
// 	{ name: "Happy Buddha", url: "happy-buddha/buddha.glb" },
// 	{ name: "Hotel Room Lotus Carpet", url: "hotel-room-lotus-carpet/scene.glb" },
// 	{ name: "Imaginary Friend Room", url: "imaginary-friend-room/scene.glb" },
// 	{ name: "Interior Scene", url: "interior-scene/scene.gltf" },
// 	{ name: "Internal Combustion Engine", url: "internal-combustion-engine/model.gltf" },
// 	{ name: "Japanese Bridge Garden", url: "japanese-bridge-garden/scene.glb" },
// 	{ name: "Japanese Temple", url: "japanese-temple/scene.gltf" },
// 	{ name: "Kitchen", url: "kitchen/scene.glb" },
// 	{ name: "Lamborghini", url: "lamborghini/scene.glb" },
// 	{ name: "Low Poly Jungle Scene", url: "low-poly-jungle-scene/scene.gltf" },
// 	{ name: "Lowpoly Space", url: "lowpoly-space/space_exploration.glb" },
// 	{ name: "Mars Site", url: "mars-site/scene.gltf" },
// 	{ name: "Material Balls", url: "material-balls/material_ball_v2.glb" },
// 	{ name: "Mercury About to Kill Argos", url: "mercury-about-to-kill-argos/scene.glb" },
// 	{ name: "Mosquito in Amber", url: "mosquito-in-amber/scene.gltf" },
// 	{ name: "NASA M2020", url: "nasa-m2020/Perseverance.glb" },
// 	{ name: "Natural Products Expo", url: "natural-products-expo/scene.glb" },
// 	{ name: "Neko Stop Diorama", url: "neko-stop-diorama/scene.gltf" },
// 	{ name: "Octocat", url: "octocat/octocat.glb" },
// 	{ name: "Octopus Tea", url: "octopus-tea/scene.gltf" },
// 	{ name: "Pathtracing Bathroom", url: "pathtracing-bathroom/modernbathroom.glb" },
// 	{ name: "Pigman", url: "pigman/scene.gltf" },
// 	{ name: "Ring Twist Halo", url: "ring-twist-halo/scene.glb" },
// 	{ name: "Scifi Toad", url: "scifi-toad/scene.gltf" },
// 	{ name: "SD Macross City Standoff Diorama", url: "sd-macross-city-standoff-diorama/scene.glb" },
// 	{ name: "Sofa Patricia", url: "sofa-patricia/scene.glb" },
// 	{ name: "Stanford Bunny", url: "stanford-bunny/bunny.glb" },
// 	{ name: "Steampunk Robot", url: "steampunk-robot/scene.gltf" },
// 	{ name: "Terrarium Robots", url: "terrarium-robots/scene.gltf" },
// 	{ name: "Threedscans", url: "threedscans/Crab.glb" },
// 	{ name: "T-Rex", url: "trex/scene.gltf" },
// 	{ name: "USD Shader Ball", url: "usd-shader-ball/usd-shaderball-scene.glb" },
// 	{ name: "Vilhelm 13", url: "vilhelm-13/vilhelm_13.glb" },
// 	{ name: "Vino Bike", url: "vino-bike/scene.gltf" },
// 	{ name: "Wooden Stylised Carriage", url: "wooden-stylised-carriage/scene.gltf" },
// 	{ name: "WW2 City Scene", url: "ww2-cityscene/scene.gltf" }
// ];

export const MODEL_FILES = [
	{ name: "Cornell Box 1", url: "/models/CornellBox1.glb", preview: "/models/CornellBox1.png" },
	{ name: "Gameboy", url: "/models/Gameboy.glb", preview: "/models/Gameboy.png" },
	{ name: "Stanford Bunny", url: "/models/StanfordBunny.glb", preview: "/models/StanfordBunny.png" },
	{ name: "Table 1", url: "/models/Table1.glb", preview: "/models/Table1.png" },
	{ name: "Table 2", url: "/models/Table2.glb", preview: "/models/Table2.png" },
	{ name: "Ambassedor", url: "/models/ambassedor.glb", preview: "/models/ambassedor.png" },
	{ name: "Antique Phone", url: "/models/antique_phone.glb", preview: "/models/antique_phone.png" },
	{ name: "Bus Traveler", url: "/models/bus_traveler.glb", preview: "/models/bus_traveler.png" },
	{ name: "C.W.M", url: "/models/c.w.m.glb", preview: "/models/c.w.png" },
	{ name: "Camera", url: "/models/camera.glb", preview: "/models/camera.png" },
	{ name: "CGT116 Week 8 - Advanced Unit Blocks", url: "/models/cgt116_week_8_-_advanced_unit_blocks.glb", preview: "/models/cgt116_week_8_-_advanced_unit_blocks.png" },
	{ name: "Diamond", url: "/models/diamond.glb", preview: "/models/diamond.png" },
	{ name: "Diorama", url: "/models/diorama.glb", preview: "/models/diorama.png" },
	{ name: "Dragon", url: "/models/dragon.glb", preview: "/models/dragon.png" },
	{ name: "Ferrari", url: "/models/ferrari.glb", preview: "/models/ferrari.png" },
	{ name: "Flashing Light Mayak C12-55M", url: "/models/ing_light_mayak_c12-55m.glb", preview: "/models/Flashing_light_mayak_c12-55m.png" },
	{ name: "Folliage", url: "/models/folliage.glb", preview: "/models/folliage.png" },
	{ name: "Gelatinous Cube", url: "/models/gelatinous_cube.glb", preview: "/models/gelatinous_cube.png" },
	{ name: "Helmet", url: "/models/helmet.glb", preview: "/models/helmet.png" },
	{ name: "Jiotto Caspita F1 Road Car 1989 by Alex.ka", url: "/models/jiotto_caspita_f1_road_car_1989_by_alex.ka.glb", preview: "/models/jiotto_caspita_f1_road_car_1989_by_alex.ka.png" },
	{ name: "Lemon", url: "/models/lemon.glb", preview: "/models/lemon.png" },
	{ name: "Mercedes Mayback", url: "/models/mercedesmayback.glb", preview: "/models/mercedesmayback.png" },
	{ name: "Model 3", url: "/models/model3.glb", preview: "/models/model3.png" },
	{ name: "Modern Bathroom", url: "/models/modernbathroom.glb", preview: "/models/modernbathroom.png" },
	{ name: "Old Stool", url: "/models/old_stool.glb", preview: "/models/old_stool.png" },
	{ name: "Outdoor Sofaset", url: "/models/outdoorsofaset.glb", preview: "/models/outdoorsofaset.png" },
	{ name: "Pagani Huayra Free", url: "/models/pagani_huayra_free.glb", preview: "/models/pagani_huayra_free.png" },
	{ name: "Retro Telephone Bordstelefon Tunnan", url: "/models/retro_telephone_bordstelefon_tunnan.glb", preview: "/models/retro_telephone_bordstelefon_tunnan.png" },
	{ name: "Road", url: "/models/road.glb", preview: "/models/road.png" },
	{ name: "Rollerskates", url: "/models/rollerskates_race_-_inliner.glb", preview: "/models/rollerskates_race_-_inliner.png" },
	{ name: "Scull Cup", url: "/models/scull_cup.glb", preview: "/models/scull_cup.png" },
	{ name: "Simple 1800s Mantel Clocks", url: "/models/simple_1800s_mantel_clocks.glb", preview: "/models/simple_1800s_mantel_clocks.png" },
	{ name: "Skatin Jade Dragon", url: "/models/skatin_jade_dragon.glb", preview: "/models/skatin_jade_dragon.png" },
	{ name: "Sony Walkman WM-F2078", url: "/models/sony_walkman_wm-f2078.glb", preview: "/models/sony_walkman_wm-f2078.png" },
	{ name: "Spyglasscase", url: "/models/spyglasscase.glb", preview: "/models/spyglasscase.png" },
	{ name: "watch Rolex Oyster Perpetual", url: "/models/watch-rolex-oyster-perpetual.glb", preview: "/models/watch-rolex-oyster-perpetual.png" },
	{ name: "Suzzane", url: "/models/suzzane.glb", preview: "/models/suzzane.png" },
	{ name: "Zenitco Klesch-2P Laser Flashlight", url: "/models/zenitco_klesch-2p__laser_flashlight.glb", preview: "/models/zenitco_klesch-2p__laser_flashlight.png" }
];

export const DEFAULT_STATE = {
	originalPixelRatio: window.devicePixelRatio / 4,
	exposure: 1,
	enableEnvironment: true,
	showBackground: true,
	model: 0,
	environment: 2,
	environmentIntensity: 1,
	fov: 75,
	focusDistance: 0.1,
	aperture: 16,
	focalLength: 0.1,
	enablePathTracer: true,
	enableAccumulation: true,
	pauseRendering: false,
	maxSamples: 100,
	bounces: 3,
	samplesPerPixel: 1,
	samplingTechnique: 1,
	adaptiveSampling: false,
	renderMode: 0,
	checkeredSize: 1,
	resolution: 0,
	directionalLightIntensity: 1,
	directionalLightColor: "#ffffff",
	directionalLightPosition: [0.3, 1, 3],
	enableOIDN: false,
	enableRealtimeDenoiser: false,
	denoiserBlurStrength: 2,
	denoiserBlurRadius: 1,
	denoiserDetailPreservation: 0.05,
	debugMode: 0,
	debugThreshold: 100
}
