/**
 * QueueManager.js
 *
 * Manages wavefront ray queues: active ray indices (ping-pong), sorted indices,
 * and GPU-side atomic counters for dynamic queue sizing.
 *
 * Counter buffer layout (4 × atomic<u32>):
 *   [0] activeRayCount    — rays alive for next bounce
 *   [1] shadowRayCount    — shadow rays generated by Shade
 *   [2] newRayCount       — rays generated by Generate
 *   [3] terminatedCount   — rays terminated this bounce
 */

import { attributeArray, storage } from 'three/tsl';
import { StorageInstancedBufferAttribute } from 'three/webgpu';

/** Counter indices — must match ResetCounters kernel */
export const COUNTER = {
	ACTIVE_RAY_COUNT: 0,
	SHADOW_RAY_COUNT: 1,
	NEW_RAY_COUNT: 2,
	TERMINATED_COUNT: 3,
	COUNT: 4,
};

/** Ray flag bits packed into rayBounceFlags (uint) */
export const RAY_FLAG = {
	BOUNCE_MASK: 0xFF, // bits 0-7: bounce count (0-255)
	ACTIVE: 1 << 8, // bit 8: ray is alive
	SPECULAR: 1 << 9, // bit 9: last bounce was specular
	INSIDE_MEDIUM: 1 << 10, // bit 10: ray is inside a transmissive medium
	// bits 11-15: ray type (for future sub-kernel dispatch)
	RAY_TYPE_SHIFT: 11,
	RAY_TYPE_MASK: 0x1F << 11,
};

export class QueueManager {

	/**
	 * @param {number} maxRays - Maximum number of rays (typically width * height)
	 */
	constructor( maxRays = 0 ) {

		/**
		 * Allocated capacity (matches RayBufferPool).
		 * @type {number}
		 */
		this.capacity = 0;

		/**
		 * Atomic counter buffer (4 × u32).
		 * @type {StorageBufferNode|null}
		 */
		this.counters = null;

		/**
		 * Active ray index buffers (ping-pong).
		 * A and B alternate: one is read by current bounce, other is written by compaction.
		 * @type {{ a: StorageBufferNode, b: StorageBufferNode }|null}
		 */
		this.activeIndices = null;

		/**
		 * Read-only views of active index buffers.
		 * @type {{ a: StorageBufferNode, b: StorageBufferNode }|null}
		 */
		this.activeIndicesRO = null;

		/**
		 * Sorted ray indices (written by Sort kernel, read by Shade kernel).
		 * @type {StorageBufferNode|null}
		 */
		this.sortedIndices = null;

		/**
		 * Read-only view of sorted indices.
		 * @type {StorageBufferNode|null}
		 */
		this.sortedIndicesRO = null;

		/**
		 * Ping-pong state: 0 = read A / write B, 1 = read B / write A.
		 * @type {number}
		 */
		this.pingPong = 0;

		if ( maxRays > 0 ) {

			this.allocate( maxRays );

		}

	}

	/**
	 * Allocate all queue buffers.
	 * @param {number} capacity - Must match RayBufferPool.allocatedCapacity
	 */
	allocate( capacity ) {

		this.dispose();
		this.capacity = capacity;

		// Atomic counter buffer: 4 × atomic<u32>
		this.counters = attributeArray( COUNTER.COUNT, 'uint' ).toAtomic();

		// Active ray indices: ping-pong pair
		// Use shared StorageInstancedBufferAttribute + count=0 so RW/RO share GPU buffer
		const attrA = new StorageInstancedBufferAttribute( new Uint32Array( capacity ), 1 );
		const attrB = new StorageInstancedBufferAttribute( new Uint32Array( capacity ), 1 );
		this._attrA = attrA;
		this._attrB = attrB;

		this.activeIndices = {
			a: storage( attrA, 'uint' ),
			b: storage( attrB, 'uint' ),
		};

		this.activeIndicesRO = {
			a: storage( attrA, 'uint' ).toReadOnly(),
			b: storage( attrB, 'uint' ).toReadOnly(),
		};

		// Sorted indices (written by Sort, read by Shade)
		const sortAttr = new StorageInstancedBufferAttribute( new Uint32Array( capacity ), 1 );
		this._sortAttr = sortAttr;
		this.sortedIndices = storage( sortAttr, 'uint' );
		this.sortedIndicesRO = storage( sortAttr, 'uint' ).toReadOnly();

		// Sort histogram: numWorkgroups × 16 atomic<u32> slots.
		// TSL lacks atomic workgroup-scoped storage, so histogram + prefix-sum
		// must live in storage memory. Each workgroup owns its own 16 slots.
		// Bin count bench (2026-04-19): 32/64 bins regress on scenes whose
		// visible material count is ≤16 (Pagani 40 materials but actually uses
		// ~16 in view regressed 29%). Only Sofaset wins with more bins.
		// A future adaptive `min(MAX_BINS, materialCount)` uniform would
		// capture both cases — see item 39.
		const SORT_WG_SIZE = 256;
		const SORT_BINS = 16;
		const numWorkgroups = Math.ceil( capacity / SORT_WG_SIZE );
		const sortHistogramSize = numWorkgroups * SORT_BINS;
		this._sortHistogramSize = sortHistogramSize;
		this.sortHistogram = attributeArray( sortHistogramSize, 'uint' ).toAtomic();

		this.pingPong = 0;

		const totalBytes = (
			COUNTER.COUNT * 4 + // counters
			capacity * 4 * 2 + // active indices A + B
			capacity * 4 + // sorted indices
			sortHistogramSize * 4 // sort histogram
		);

		console.log(
			`QueueManager: Allocated capacity=${capacity}, ` +
			`total=${( totalBytes / ( 1024 * 1024 ) ).toFixed( 1 )} MB`
		);

	}

	/**
	 * Resize if needed. Returns true if reallocation occurred.
	 * @param {number} capacity
	 * @returns {boolean}
	 */
	resize( capacity ) {

		if ( capacity <= this.capacity && this.capacity > 0 ) return false;
		this.allocate( capacity );
		return true;

	}

	/**
	 * Get the atomic counter node (read-write).
	 * @returns {StorageBufferNode}
	 */
	getCounters() {

		return this.counters;

	}

	/**
	 * Get the active indices buffer to READ from (current ping-pong side).
	 * @returns {StorageBufferNode}
	 */
	getActiveReadRO() {

		return this.pingPong === 0 ? this.activeIndicesRO.a : this.activeIndicesRO.b;

	}

	/**
	 * Get the active indices buffer to READ from (RW version for compaction input).
	 * @returns {StorageBufferNode}
	 */
	getActiveRead() {

		return this.pingPong === 0 ? this.activeIndices.a : this.activeIndices.b;

	}

	/**
	 * Get the active indices buffer to WRITE to (opposite ping-pong side).
	 * @returns {StorageBufferNode}
	 */
	getActiveWrite() {

		return this.pingPong === 0 ? this.activeIndices.b : this.activeIndices.a;

	}

	/**
	 * Get sorted indices (read-write for Sort kernel).
	 * @returns {StorageBufferNode}
	 */
	getSortedRW() {

		return this.sortedIndices;

	}

	/**
	 * Get sort histogram (atomic read-write for Sort kernel).
	 * @returns {StorageBufferNode}
	 */
	getSortHistogram() {

		return this.sortHistogram;

	}

	/**
	 * Number of u32 slots in sort histogram (numWorkgroups × 16).
	 * @returns {number}
	 */
	getSortHistogramSize() {

		return this._sortHistogramSize;

	}

	/**
	 * Get sorted indices (read-only for Shade kernel).
	 * @returns {StorageBufferNode}
	 */
	getSortedRO() {

		return this.sortedIndicesRO;

	}

	/**
	 * Swap ping-pong buffers. Called after compaction.
	 */
	swap() {

		this.pingPong = 1 - this.pingPong;

	}

	/**
	 * Reset ping-pong state (start of new frame).
	 */
	resetPingPong() {

		this.pingPong = 0;

	}

	dispose() {

		this.counters = null;
		this.activeIndices = null;
		this.activeIndicesRO = null;
		this.sortedIndices = null;
		this.sortedIndicesRO = null;
		this.capacity = 0;

	}

}
