name: Release

on:
  push:
    branches: ['main']

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for git history and tags

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Get version from git tag
        id: get-version
        run: echo "VERSION=$(git describe --tags --abbrev=0 || echo '0.0.0')" >> $GITHUB_ENV
      
      - run: npm ci
      - run: npm run build
        env:
          PACKAGE_VERSION: ${{ env.VERSION }}
          
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}